### ISSUE TITLE
ロッカー利用者検索のクエリパラメータについて

### ISSUE THREAD

**Issue by Lit-innosence** [Lit-innosence/tus_yuurikai_system#20]
## 概要
ロッカー利用者検索において、assignment_recordおよびstudent_pairレコードから抽出する前に、クエリパラメータであるnameを処理しなければいけません。
このとき、nameの候補が多く処理量が膨らんでしまうのでできれば変更したいです。
- family_name
- given_name
- family_nameとgiven_nameの両方

この際、クエリパラメータを変更することで問題が解消すると思われますが、代替案であるクエリパラメータの候補がいくつかあります。

- 代わりにfamily_nameとgiven_nameを追加する
- 代わりにstudent_idを追加する
- family_name、given_name、student_idのどれも追加する

上記代替案のうちどれが良いか意見をいただきたいです。
また他の代替案があれば考えていただきたいです。

**Comment by Dot-P** [comment]
とりあえずfamily_name、given_nameをクエリパラメータにするのでよいかと

**Comment by Lit-innosence** [comment]
とりあえずその方向で実装しようと思います
