### ISSUE TITLE
学生情報の更新処理

### ISSUE THREAD

**Issue by Dot-P** [Lit-innosence/tus_yuurikai_system#9]
## 概要
利用二年目以降、学生情報の登録においてupdated_atを更新します。
ここで、どの属性が一致したときにupdated_atを更新するのかが非常に悩ましいです。候補としていかが挙げられます。
- student_id
- family_name と given_name
- student_idとfamily_nameとgiven_name

しかし、それぞれ以下の問題を抱えます。

- ある学生が誤った学籍番号を登録した際に、updated_atが更新されてしまう(student_id)
- 同姓同名が存在しうるかもしれない(family_name、given_name)
- 両親の結婚、離婚による姓の変更があった場合に、更新異常が発生。内部サーバーエラーを返します。(student_id, family_name, given_name) 
## 要望
どれにするのがよいか意見をいただきたいです。
開発はとりあえずstudent_idで進めます。(変更は容易です)

**Comment by Lit-innosence** [comment]
student_idが学生に固有であるため，これを採用するのがわかりやすいと思います．

採用によって発生する，誤った学生情報の登録といった問題点は，更新時に再度メールアドレス認証を要求することで解決すると思われますがどうでしょうか．

**Comment by Dot-P** [comment]
そうなると、システム構成が変わると思います。
一度、学生情報を一時データベースに保存しないといけないので、

学生情報入力 -> メール送信・一時データベース保存 -> メール認証・一時データベース内容を移動 -> ロッカー照会 -> ...

になります。
APIの処理が変わるので現在行っているユーザー情報登録の処理を分割する必要があります。

**Comment by Dot-P** [comment]
私がメール送信の処理を書けば問題ないような気もしますが。

**Comment by Lit-innosence** [comment]
> 学生情報入力 -> メール送信・一時データベース保存 -> メール認証・一時データベース内容を移動 -> ロッカー照会 -> ...

メールアドレス認証を行う場合に上記の順序で処理を行うとすれば，初めて登録をする際にもこの手順が必要になるので，システム構成の変更は避けられないと思われます．

また，学生情報を登録する処理中にメールアドレス認証を非同期処理で挟みこむことでシステム構成の変更は避けられると思いますがこちらはどうでしょうか．

学生情報入力 -> 学生情報登録（await でメール認証を呼びだす） -> メール認証 -> 学生情報登録 -> ロッカー照会 -> ...

**Comment by Dot-P** [comment]
> メールアドレス認証を非同期処理で挟みこむ

- 非同期であっても、タブを閉じるなどといった誤動作により情報喪失が起こる？
- 非同期処理は基本的にバグを増やすので極力避けたい

といった観点があるのでできるだけ避けたいです。
なので、システム構成の変更をしたいと思うのですがいかがでしょうか。

**Comment by Lit-innosence** [comment]
> 非同期処理は基本的にバグを増やすので極力避けたい
バグを増やしかねないのは確かに避けたいですね。
システム構成を変更する方向でお願いします。

**Comment by Dot-P** [comment]
学生情報の登録のAPIが一時データベースへの格納に役割が変更になり、現在の処理がメール認証に役割が譲渡されます。
そのため、メール認証も私が担当しようと思っているのですが、大丈夫でしょうか。
今後の予定としては、

StudentPairも含めて一度作り切る(ユニットテストは行わない)
 -> 処理を適切なAPIに割当て、学生情報の登録を作りきり、ユニットテスト

にしようと思っています。

**Comment by Lit-innosence** [comment]
確認になりますが，
- 一時データベースに保存するAPI
- メール認証と学生情報登録のAPI (現在作成しているAPIに機能を追加)
の2つに処理を分けるという認識でよろしいでしょうか．
進め方には異論ありません．

**Comment by Dot-P** [comment]
API名が逆な気がします。

> 一時データベースに保存するAPI

この学生情報の登録を一時データベースに保存するAPIを"/user-register"に、
メール認証(受取り)&一時データベースから本登録データベースへの移動を"/mail-auth"?に追加する予定です。
今書いているコードはどちらにもまたがっているので、処理を分けます。
